environment:
  name: preprod

deployment:
  namespace: luxsoft-preprod

docker:
  registry: docker.io
  image_name: luxsoft

build:
  optimization: true

logging:
  level: INFO

security:
  trivy_fail_on_high: true